server:
    port: 8080

spring:

  main:
    allow-circular-references: true

  application:
    name: lanchonete

    # H2 configuration
    datasource:
      #url: jdbc:h2:mem:lanchonetedb
      url: jdbc:mysql://terraform-20241130022029869400000001.c3sc02woof7e.us-east-1.rds.amazonaws.com:3306/lanchonetedb
      username: sa
      password: password123
      #driverClassName: org.h2.Driver
      driverClassName: com.mysql.cj.jdbc.Driver
   # h2:
   #   console:
   #     enabled: true
   #     path: /h2-console
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        #database-platform: org.hibernate.dialect.H2Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
      properties:
        hibernate:
          format_sql: true

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs

# Swagger
  swagger-ui:
    path: /swagger-ui.html

