apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-loadbalancer-svc
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysqldb-pod
  type: LoadBalancer
