apiVersion: v1
kind: Pod
metadata:
  name: mysqldb-pod
  labels:
        app: mysqldb-pod
spec:
  containers:
    - name: mysqldb
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "lanchonetedb"
        - name: MYSQL_USER
          value: "sa"
        - name: MYSQL_PASSWORD
          value: "password"
