name: CI/CD Pipeline

on:
  push:
    branches:
      - main 

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: mvn test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1

  code-analysis:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=Devops-Fiap

  build-and-push:
    runs-on: ubuntu-latest
    needs: [unit-test, code-analysis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        env:
          ECR_REPOSITORY: my-ecr-repository # Substitua pelo nome do repositório ECR
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          
          # Tag the image for ECR
          docker tag $ECR_REPOSITORY:$IMAGE_TAG <aws_account_id>.dkr.ecr.<region>.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          
          # Push to ECR
          docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

  update-eks:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Configure kubectl
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: <region> # Substitua pela região da AWS (ex.: us-east-1)

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/my-deployment my-container=<aws_account_id>.dkr.ecr.<region>.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}
          kubectl rollout restart deployment/my-deployment
