apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  MYSQL_URL: jdbc:mysql://a66fa3f7b1d0b4e9ab480571a23dfecb-579988863.us-east-1.elb.amazonaws.com:3306/lanchonetedb
  MYSQL_USERNAME: sa
  MYSQL_PASSWORD: password
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
